#Download mediawiki setup url
mediawiki_url: https://releases.wikimedia.org/mediawiki/1.36/mediawiki-1.36.0.tar.gz
#Version details
mediawiki_version: mediawiki-1.36.0
# 3rd party repo
epel:
  - centos-release-scl
  - epel-release

#Required Packages for Apache , PHP and MySQL
web_pkgs:
 - python-pip
 - httpd24-httpd
 - wget
 - rh-php73
 - rh-php73-php
 - rh-php73-php-intl
 - rh-php73-php-mbstring
 - rh-php73-php-mysqlnd
 - rh-php73-php-gd
 - rh-php73-php-xml
 - mariadb-server
 - mariadb

# Required pkg from remi repo
remi_pkgs:
 - php