mediawiki_url: https://releases.mediawiki.org/mediawiki/1.36/mediawiki-1.36.0.tar.gz
mediawiki_version: mediawiki-1.36.0
web_pkgs:
 - python-pip
 - epel-release
 - centos-release-scl
 - httpd24-httpd
 - wget
 - rh-php73
 - rh-php73-php
 - rh-php73-php-mbstring
 - rh-php73-php-mysqlnd
 - rh-php73-php-gd
 - rh-php73-php-xml
 - mariadb-server
 - mariadb

remi_pkgs:
 - php
 - php-intl