---
# tasks file for mediawiki
- block:

  - name: Include Localized Variable File(s)
    include_vars: "{{ item }}"
    with_items:
       "{{ role_vars }}"
 
  - debug: msg="Running mediawiki installation on  Instance  {{ item }}"
    with_items:
      - "{{ groups.mediawiki }}"
 
  - include: install_pkgs.yml
 #   delegate_to: "{{ item }}"
#    with_items:
 #    - "{{ groups.mediawiki }}"
    loop: "{{ groups['mediawiki'] }}"


  - name: Copy .pem File From S3
    command: "aws s3 cp s3://{{ s3_key_file_path }}/{{key_file}}.pem {{ role_path}}/files/{{key_file}}.pem --region {{region}}"
    environment: "{{ environment_vars }}"