---
# tasks file for mediawiki apache setup
- block:

  - name: Include Localized Variable File(s)
    include_vars: "{{ item }}"
    with_items:
       "{{ role_vars }}"
 
  - debug: msg="Running mediawiki installation on  Instance  {{ item }}"
    with_items:
      - "{{ groups.mediawiki }}"
 
  - include: install_pkgs.yml
 #   delegate_to: "{{ item }}"
#    with_items:
 #    - "{{ groups.mediawiki }}"
    loop: "{{ groups['mediawiki'] }}"
